"""Task model and TaskStatus enum."""

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, field_validator


class TaskStatus(str, Enum):
    """Task completion status."""

    PENDING = "PENDING"
    COMPLETED = "COMPLETED"


class Task(BaseModel):
    """Todo task with unique ID, title, description, and status.

    Attributes:
        id: Unique positive integer identifier (auto-generated by repository)
        title: Required non-empty task title (max 200 characters)
        description: Optional task description (max 1000 characters)
        status: Task completion status (PENDING or COMPLETED)
    """

    id: int = Field(default=0, ge=1, description="Unique task ID")
    title: str = Field(min_length=1, max_length=200, description="Task title")
    description: str = Field(default="", max_length=1000, description="Task description")
    status: TaskStatus = Field(default=TaskStatus.PENDING, description="Completion status")

    model_config = ConfigDict(use_enum_values=False, frozen=False)

    @field_validator("title")
    @classmethod
    def title_not_empty(cls, v: str) -> str:
        """Validate title is not empty or whitespace-only."""
        if not v or not v.strip():
            raise ValueError("Title cannot be empty or whitespace-only")
        return v.strip()
